### ISSUE TITLE
Using with ES6 classes

### ISSUE THREAD

**Issue by neptunian** [thejameskyle/react-required-if#1]
Can this work when creating the component with an ES6 class where prop types and default props are declared outside the component?

https://facebook.github.io/react/docs/reusable-components.html#es6-classes

**Comment by thejameskyle** [comment]
Yes

**Comment by neptunian** [comment]
@thejameskyle Sorry, I thought it wasn't working because I was declaring it outside the component.  But the issue I'm having is I'm trying to use RequiredIf in a propType down a level:

`Gallery.propTypes = {
    photos: React.PropTypes.arrayOf(
        React.PropTypes.shape({
            src: React.PropTypes.string.isRequired, 
            width: React.PropTypes.number.isRequired,
            height: React.PropTypes.number.isRequired,
            aspectRatio: React.PropTypes.number.isRequired,
            lightboxImage: RequiredIf(React.PropTypes.object, props => !props.disableLightbox)
        })  
    ).isRequired,
    disableLightbox: React.PropTypes.bool
};      

Is there a way to get the properties for the next level up?`
